{% set name = "litedao" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litedao-{{ version }}.tar.gz
  sha256: 74ea066877aff86a04d5c8e607b8bf5098cb45cc3d18711fcc151ce9bb62857c

build:
  entry_points:
    - litedao = litedao.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - litedao
  commands:
    - pip check
    - litedao --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/litedao
  summary: Intuitive interaction with SQLite database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
